version: "2.1"

volumes:
  groute-keys: {}

services:
  groute:
    build: .
    restart: always
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
      - "10000-20000:10000-20000"
    volumes:
      - "groute-keys:/app/keys"
